dist: trusty
sudo: false
git:
  depth: false
addons:
  apt:
    packages:
      - language-pack-it
      - curl
      - autoconf
      - automake
      - libtool
      - python-dev
      - pkg-config
  sonarcloud:
    organization: lucacappelletti94-github
    token:
      secure: 0m+C4vE665JtfviPRe95tZXSOW4dMw9tjsA25QyMIhTdJg1ShmU6PJ8fe9C5swm7qNwLwjo4C92ekdvE/SD6EuBbH33YX16wPzYie3XtlHw/LalGDlah6pN25Kwn+7falWqsfGoYUhZBmxXG6PTkJcT352ZvCuwR4ZwmCdUNOrB9VwNNRKSUZPoYREiQcjOBw0NE6bWj4GLeqIhv2KhKomvPprzrSkjV2JBY7bybmWcxwwz6HcyMpdZDSy6e5QyAr/xrcBa+8uGXooOVil+Mpw45YbpJ6dCoac6EDFtmoFppcVz4/anVtliz6Vcyq44BDPrYneeAbARWghpKA1YYOBO6JEPJLKTV9qRLvE2YLpOWe+CuZuvhkGJVKXfKNNFAHhYk8vsJlITWiuifn4em20SGk29nQtCgPkOyGYwn6JahrxUmls8WAwbQ0kIC16+1ff7ATRklo2FtxmFYBWJQpljg9mpE7ElcvXSCdlrLSYl2ZeAlWiXSG6i98jrY/khCCHJSm4gMLy2IgtWie8hpU2RlBsneGqrU4W5xyZH/oyCXBxJWhgluBZW6XZOl8F4Yd4mBehpnHYJmI/2lzgcL711EgaPEuMF2LieOEQpBf1POLN6FkUHmY6N6A4sN6LNW3uMBznK82l/HOgVXrLqplfNNjEZ81cF0m3pyDpx+WV0=
language: python
python:
- '3.6'
before_install:
- pip install --upgrade pytest
- curl https://raw.githubusercontent.com/LucaCappelletti94/italian_csv_type_prediction/master/setup.sh | sudo sh
- sudo ldconfig
install:
- pip install .[test]
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=csv_trimming --cov-report xml:coverage.xml
- coverage combine --append || true
- coverage report
- coverage xml
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi
after_success:
- coveralls
- python-codacy-coverage -r coverage.xml
env:
  global:
  - secure: Jk7tcCKmZAWPj8XVDUoJvcG4Xr9ZMKpvxWifSvMhmOOEZzvtHVJrnG2y3sp/z9HQYtqMkPflH/NTElrYtNB/0XSuBjWUcvvvC33Z842jJVJziDeD1tWbijkNM0U/Pf8r4E5aW1DnsGtM8lcd5L2DQdyWDZEJsBXzsfXO+X3agqTxfUzrQroAO/cL/jcUVeHLeYn4WP7SVkeEMp3mMchd5ixNTdgRuq7zi6QQS8TFCnHg9pdH0C50JFTpUcCN1vCeyDD0UARacZXQkbWJaFOzkof481tyXw3392Cb7g5LnI8ss4GWWmjm/moebv822h4N5FrmDkXzB5KRyw1Tetuk7bqYOX2QcW2LC2U4oBcujtThxAjWr9j3Axr/HOiPfrjzRFxM13H4/e0bcyUldfwEhfphP5lTuKLaQzk5Gwo5s6O6zx8LEJlnurTfqPOXSHAnmItMKwzveqyH/r5vkzBksSf5dH1A6lOoXgoD3/jcL2FZEqooFlCd7+cKrzIR02UqfVAruIjIAeZTgLUWTkEWWAT+gaTQq9wHMsVJ1OtUtIz2Tc9EzHG6EoeE4+IEWXhwFaYV8hbeukerxINV3rBCe4niEUx3D/Dt7j3MAGywCcUwwT/sbQiucNpB2phPofJHenLYH0sjLpbS0PBNj5ASTW+DeLFG1f1YnPPcOFl40uw=
  - secure: vmiBQd2LIyda72qCTzCu6NgaqGIdWUuT1Qty+qhneZcf57N9p0vdJwz1dpTmvsyzSl6OB5QgG9kiL2lJBq3XXDtyTwQIGFYBUU9++x80TN+1KulxTu/+CORzOQ6ndz2MtA9S+SARkb/+Zo5IqG5i27I2qIZgVu3GaYI2I9VRXyfM9SnJ9nUoBMciMx9rIAGBlGspkSE2gY5Ml2yrkwR58x0uWtD14e85bQD2Wj529O7bFYyWtKxI5FKSNKKQJQG6ug1e4Fx5XuDfgAE+PWiGjFymuN7zcGkO1hi1J4mTo2+tllSJb/elP/fA42mPRLOjiefgaAErT+XCjJJP/0e/5pRUDsyvBiTVRf3ZgB66MSk8nqIeVLVXF0AGM15Gc6JrifIZ8sVhi49XYFnQOF3MX01s4CNPh5/qPtmtyOLA2JlALlcF+jH0hDjHpLne4HXm4g3N5Nbsx5oFRxifkaX/AUaosxbFjJJS+yjA+lzGm4g3D8Tyt1GR7ttIroBvbzgMonol3TrENzDEI5f7mbE09ulZHBJGp775qhXcfXexYezsISubaFt1Y5i3winiNF9DRLOMSO0LBUqjeoij4Ozlsrp8cEonoXgMW+FOmTGNUBIsvg+m5jwtGaKb5EWJvUtThplFenIakueD0ka/MQkigThhExKlw/AH9W/8lRo1bQU=
  - secure: BLY7wGvbUbHXc7+av2yKnZXqMZI7vgA+ju+0u8Duh7ttv3E656PEs5iw+RzGp+LZHJmxqguL0sPk+7CXJTNdRchTF7Pm+6sb0sVnr5ir9T01CKRDaWzvnvFzS5japjr/PKUmLyZxQuRuapXr1NoGQHWNItmk6uznYvwaLR4KQqUNL8ExlqgxLEGj3RAFJ+itGKvmKz6xK0FENwOhbrNOjTxli9OUiHU3+vpyF+xFRVvGsnx4HTLH/7VoQ5nCKWzOSJOscHY4AJdYCdLPrvZddjwx2TmafBeJt27ED915Aqu74HnSqI+8bvf0GsrAzzIyW46u32OgJZ53b04d02B9H1xQZZk4kKWcnb+H45VM61tmeqRgMORlxOeXoFAlY5nAJyMI9hOPCvUD9e3b6zsBehUvV6k+b2MMIUnKz/2R2upCZZio0CS6r5bbSH6dbqV/O58gLPQJ3jvQvmxoK/O59M8V4qxtGuHDQltUORElW5qoSO4jdHnZO4ssQ3Igxe7DWRtfSK9bThfrBWo7hfxncgYVN761S1SxkWZtNJK0u0jEjsKviL+tmcWvzCB5tOeNW19H7CLwoLMbTx1qG7ORI9GM05hU6/Y5WaXd8wDHqJ1R1+uXsrxv/ChvYdQi8J+3NENtCYMuVIH6q9Z2fsESn1cNgSqSXQCxDMphpxAA5EA=
